# 7章 CNN(畳み込みニューラルネットワーク)

## Numpy 補足
### Transpose
配列の形を変形する

In [53]:
import numpy as np
np_mat = np.array([[[1,2,3]],[[4,5,6]]])
print(np_mat)
print(np_mat.shape) #=> (2, 1, 3)

[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)


In [52]:
transposed = np_mat.transpose(1,0, 2)
print(transposed.shape) #=> (1,2,3)
print(transposed)

(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


## Reshape
### 配列アクセスの復習



In [61]:
np_ar = np.array([1,2,3,4,5,6,7,8])
print(np_ar[1:5] )#=> array([2, 3, 4, 5])

[2 3 4 5]


In [57]:
# 0番目から6番目までを２つおきに
print(np_ar[0:6:2]) #=> array([1, 3, 5])

[1 3 5]


In [58]:
# すべて取得
print(np_ar[:]) #=> array([1, 2, 3, 4, 5, 6, 7, 8])

[1 2 3 4 5 6 7 8]


In [59]:
# 負のインデックスを指定
print(np_ar[1:-1]) #=> array([2, 3, 4, 5, 6, 7])

[2 3 4 5 6 7]


In [62]:
np_mat = np.array([[1,2,3],[4,5,6]])
print(np_mat.shape) #=> (2, 3)

(2, 3)


In [63]:
reshaped_mat = np_mat.reshape(3, 2)
print(reshaped_mat.shape) #=> (3, 2)
print(reshaped_mat)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [64]:
# reshapeは、配列の中にある数字の個数を変更することはできないことがポイント
# 2×3=6 と 1×2=2を比較してもおかしい
reshaped_mat_error = reshaped_mat.reshape(1, 2)

ValueError: cannot reshape array of size 6 into shape (1,2)

In [69]:
# -1を追加することで、綺麗な形に変換できることもある
from prettyprinter import cpprint
reshaped_mat_no_error = reshaped_mat.reshape(1, 2, -1)
cpprint(reshaped_mat_no_error)

array([[[1, 2, 3],
        [4, 5, 6]]])


## 用語の説明

* Convolution layer : 畳み込み層
* 畳み込み演算  
   ・・・入力データに対して、Fliter(kernel) を通した処理を行うこと  
  * Padding : 入力データの周囲に固定データを埋め込むこと
  * Stride : フィルターを適用する間隔
* Pooling layer : プーリング層  
   ・・・縦横の次元を減らす処理、特徴抽出の1手法  
   * 学習するパラメータがない
   * 微小な位置変化に対してロバスト(頑健)

## AlexNet
現在、メインとなっているCNNの一つ。以下の特徴がある。
* 活性化関数にRelu関数を用いる
* LRNという局所的正規化を行う層を実装する
* Dropoutを使用する